# Generated by Django 2.2.25 on 2021-12-09 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windspeed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_number', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('is_handle', models.BooleanField()),
                ('is_cutter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('mascot', models.CharField(max_length=50)),
                ('overall_rating', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.League')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('turnovers', models.PositiveIntegerField(default=0)),
                ('completions', models.PositiveIntegerField(default=0)),
                ('throwaways', models.PositiveIntegerField(default=0)),
                ('drops', models.PositiveIntegerField(default=0)),
                ('passing_yards', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('touches', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.Game')),
                ('player', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teamOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamOne', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='teamTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamTwo', to='FrisbeeApp.Team'),
        ),
    ]
