# Generated by Django 2.2.25 on 2021-12-10 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrisbeeApp', '0002_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('turnovers', models.PositiveIntegerField(default=0)),
                ('completions', models.PositiveIntegerField(default=0)),
                ('throwaways', models.PositiveIntegerField(default=0)),
                ('drops', models.PositiveIntegerField(default=0)),
                ('passing_yards', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('touches', models.PositiveIntegerField(default=0)),
                ('league_season', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.LeagueSeason')),
                ('player', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one_score', models.IntegerField(default=0)),
                ('team_two_score', models.IntegerField(default=0)),
                ('league_season', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.LeagueSeason')),
                ('loser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='season_game_loser', to='FrisbeeApp.Team')),
                ('team_one', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='season_game_team_one', to='FrisbeeApp.Team')),
                ('team_two', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='season_game_team_two', to='FrisbeeApp.Team')),
                ('winner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='season_game_winner', to='FrisbeeApp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('throwaways', models.IntegerField(default=0)),
                ('drops', models.IntegerField(default=0)),
                ('breaks', models.IntegerField(default=0)),
                ('league_season', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.LeagueSeason')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='team_eight',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_eight', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_five',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_five', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_four',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_four', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_nine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_nine', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_one',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_one', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_seven',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_seven', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_six',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_six', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_ten',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_ten', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_three',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_three', to='FrisbeeApp.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='team_two',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_two', to='FrisbeeApp.Team'),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.TeamGame'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='leagueseason',
            name='league',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FrisbeeApp.League'),
        ),
    ]
