# Generated by Django 2.2.25 on 2021-12-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrisbeeApp', '0003_auto_20211209_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='team_eight',
        ),
    ]
