# Generated by Django 2.2.25 on 2021-12-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrisbeeApp', '0004_remove_league_team_eight'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='team_eight',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='league_team_eight', to='FrisbeeApp.Team'),
        ),
    ]
